---
sudo: false
language: c++
# dotnet cli require Ubuntu 14.04
sudo: required
dist: trusty

# dotnet cli require OSX 10.10
osx_image: xcode7.1

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

os:
  - osx
  - linux

env:
  matrix:
    - CLI_VERSION: Latest
      Configuration: Debug
    - CLI_VERSION: Latest
      Configuration: Release

before_install:
  # Install OpenSSL
  - if test "$TRAVIS_OS_NAME" == "osx"; then
      brew update;
      brew install openssl;
      brew link --force openssl;
    fi

  # Download script to install dotnet cli
  - curl -L --create-dirs https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh -o ./scripts/install.sh

  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"

  # Install the latest versio of dotnet CLI
  - bash ./scripts/install.sh --channel "beta" --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR" --no-path

  # Add dotnet to PATH
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

install:
  # Display dotnet version info
  - which dotnet;
    if [ $? -eq 0 ]; then
      echo "Using dotnet:";
      dotnet --info;
    else
      echo "dotnet.exe not found"
      exit 1;
    fi

  # Restore dependencies
  - dotnet restore

  # Build projects
  - dotnet build -c $Configuration ./test/NUnit.Portable.Agent.Tests

script:
  # Run tests
  - dotnet run -c $Configuration -p ./test/NUnit.Portable.Agent.Tests
